"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import { GlobalContextProvider } from "@/context/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GlobalContextProvider>
        <SessionProvider>
          <body className={inter.className}>
            {children}
            <Toaster
              position="top-center"
              containerStyle={{
                top: 100,
              }}
            />
          </body>
        </SessionProvider>
      </GlobalContextProvider>
    </html>
  );
}
